oboro => [prepare-commit-msg]

diff --git a/runes/git/template/hooks/prepare-commit-msg b/runes/git/template/hooks/prepare-commit-msg
--- a/runes/git/template/hooks/prepare-commit-msg
+++ b/runes/git/template/hooks/prepare-commit-msg
@@ -21,15 +21,19 @@ fi
 
 # Assuming a JIRA key looks like:
 #   Two or more capital letters, a dash, and some numbers
-JIRA_REGEX="\b[A-Z]\{2,\}-[0-9]\+\b"
+JIRA_REGEX="\b[a-zA-Z]\{2,\}-[0-9]\+\b"
 
 # Find the JIRA in the branch name
 JIRA_ID=$( git symbolic-ref --short HEAD | grep -o "$JIRA_REGEX" )
 
 # Couldn't find a JIRA key in branch name, just stop.
 [ -z "$JIRA_ID" ] && {
-    [ ! -e mendess-require-ticket-number ]
-    exit
+    if [ -e mendess-require-ticket-number ]; then
+        echo "missing ticket number in commit message"
+        exit 1
+    else
+        exit 0
+    fi
 }
 
 
